version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: spring_user
      MYSQL_PASSWORD: spring_user_password
      MYSQL_DATABASE: backend

  spring-boot-app:
      build:
        context: ./server
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - mysql
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/backend
        SPRING_DATASOURCE_USERNAME: spring_user
        SPRING_DATASOURCE_PASSWORD: spring_user_password

  react-app:
      build:
        context: ./client
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
